---
- name: Update repository and Upgrade packages
  apt:
    upgrade: dist
    update_cache: yes

- name: Install Nignx
  apt:
    name: nginx
    state: latest
    update_cache: yes

- name: Copy holding page for Nginx Specific
  template:
    src: templates/webserver01.al.local.html
    dest: /var/www/html/index.nginx-debian.html
    owner: root
    group: root
    mode: u=rwx,g=r,o=r 
    
- name: restart nginx
  service: 
    name: nginx
    state: restarted 
    enabled: yes

