---

# 1st Loadbalancer

- hosts: loadbalancer01.al.local

- vars:
    http_port: 80

- tasks:

- name: ensure nginx is installed 
  apt: 
   name: nginx 
   state: latest
   update_cache: yes
   become: yes
- name: start nginx
  service:
    name: nginx
    state: started
    become: yes

- name: Copy Nginx config file 
  template:
    src: templates/lb_nginx.conf
    dest: /etc/nginx/conf.d/lb_nginx.conf
    owner: nginx
    group: nginx
    mode: u=rw,g=r,o=r
    become: yes
- name: Ansible check file exists example.
  stat:
    path: /etc/nginx/conf.d/lb_nginx.conf
    register: file_details
    become: yes
- debug:
    msg: "The Nginx config file or directory exists"
    when: file_details.stat.exists
    become: yes