---

#2nd webserver
- hostname:
    name: webserver02.al.local
    ansible_ssh_host: 10.0.0.15
    ansible_ssh_port: 22
    ansible_ssh_user: vagrant
    
- hosts: all

- vars:
    http_port: 80

- tasks:

- name: ensure nginx is installed 
  apt: 
   name: nginx 
   state: latest
   update_cache: yes
   become: yes
   notify:
      - start nginx

- name: start nginx
  service:
    name: nginx
    state: started
    become: yes
- name: Creates directory this project site config directory al.local directory
  file:
    path: /etc/nginx/sites-available/al.local 
    state: directory
    owner: nginx
    group: nginx
    mode: u=rw,g=r,o=r

- name: Creates directory this project site web_www directory al.local directory
  file:
    path: /var/www/al.local 
    state: directory
    owner: nginx
    group: nginx
    mode: u=rw,g=r,o=r

- name: Copy Nginx config file 
  template:
    src: templates/al.local.conf
    dest: /etc/nginx/sites-available/al.local/al.local.conf
    owner: nginx
    group: nginx
    mode: u=rw,g=r,o=r

- name: Ansible check file exists example.
  stat:
    path: /etc/nginx/conf.d/nginx.conf
    register: file_details

- debug:
    msg: "The Nginx config file or directory exists"
    when: file_details.stat.exists

- name: Copy holding page for Nginx Specific
  template:
    src: templates/webserver02.al.local.html
    dest: /var/www/al.local/index.html
    owner: nginx
    group: nginx
    mode: u=rw,g=r,o=r 

    
